backend:
  name: github
  repo: soulsam480/ecom-test
media_folder: "public/img"
public_folder: "/img"

collections:
  - label: "Products"
    name: "products"
    files:
      - label: "Product"
        name: "product"
        file: "src/assets/content/storedata.json"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          